README.md

Since it has been decided that ports should stay on different repos here it is the link ;)

Add Python 3 port to README

---

README.md

Adds runeterra to the implementations section

Add our JavaScript port

---

README.md

my lib only decodes deckstrings but planning to do encoding too

feat(readme): add golang thirdparty-lib

---

README.md

In order of initial submission. It's only fair...

Add python3 implementation link to README.md

---

README.md

Hey,
I just made this library to share it with the community.
I would appreciate it if you to add this library to the implementations list.

Add RuneTerraPHP Library to the list of implementations

---

README.md

I'd like to add a package for the Julia language.
thanks.

Add Julia port to README

---

README.md

Add Snowcola's python3 implementation to the readme

Add Snowcola's python3 implementation to the readme

---

README.md

The Java port wasn't working on Android, so I made a new one for Android 15+.
I hope this will help you for the mobile version of the game

Added Android port to the readme

---

README.md

Updated version of mike-reinders/runeterra-php to 2.
`Added Bilgewater faction`
Greetings, BlindFox2015

Update version to 2 in README.md

---

README.md

Hi! I've made another Ruby port, it would be great if it could be added to the README. Thank you!

Add runeterra_cards Ruby library to README.md

---

README.md

I updated the library and its supported deck code version to 3!
Greetings BlindFox2015

Update RuneTerraPHP library supported version to 3

---

README.md

I've created an up-to-date TypeScript implementation of the project and added a reference to the "Implementations" table.

Add Project to Implementations

---

README.md

Add link to an [R implementation](https://github.com/pholzmgit/lordecks) in README.md
test protocol:

Update README.md with R implementation

---

README.md

Added Bandle City support to R implementation.

Update README with v4 support of R implementation

---

README.md

I created a new Java implementation to develop an app.
The existing implementation was in a repo with a lot of other stuff so I made my own version.
The project is only a encoder/decoder for the deck codes, written in Java

Added new Java implementation

---

README.md

https://github.com/Billzabob/ForDeckmacia/commit/7ca33ede887247b9d8f1741bc2bcad0b5d34a5cf

Update ForDeckmacia to version 5

---

LoRDeckCodes/LoRDeckEncoder.cs
LoRDeckCodes_Tests/UnitTest1.cs

* Add support for Runeterra faction
* Clean up constants/tests

Add support for Runeterra faction

---

README.md

Added support for Runeterra Faction

Update README with v5 support for R implementation

---

README.md

Python package manager updated as well
CC: @RiotTuxedo

Update the python 3 implementation version

---

README.md

Faster and more efficient (less memory allocation) implementation in C#.

Add C# implementation
